version: '3.7'

services:
  database:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminuser12345
      POSTGRES_DB: form_app
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: